ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "paymentProofUrl" VARCHAR(255);
ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "paymentProofUploadedAt" TIMESTAMP;
ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "bankTransferData" JSONB;
